language: python
python:
  - "2.7"
install:
  - pip install -q -r requirements.txt --use-mirrors
script:
  - python setup.py test
notifications:
  irc:
    channels:
        - "irc.ox.ac.uk#mox"
    on_success: change
